[pack]
namespace = "jc"
name      = "coder"
version   = "0.1.3"

# -- Optional section
license  = "MIT or Apache 2"
homepage = "https://aipack.ai/"
repo     = "https://github.com/aipack-ai/packs-jc"
author   = "Jeremy Chone"

